production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailer_host: <%= ENV["MAILER_HOST"] %>
  mailer_address: <%= ENV["MAILER_ADDRESS"] %>
  mailer_port: <%= ENV["MAILER_PORT"] %>
  mailer_user_name: <%= ENV["MAILER_USER_NAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  fog_directory: <%= ENV["FOG_DIRECTORY"] %>
  sentry_key: <%= ENV["SENTRY_KEY"] %>
  sentry_secret: <%= ENV["SENTRY_SECRET"] %>
  sendgrid_api_key: <%= ENV["SENDGRID_API_KEY"] %>